---
title: "Statistique"
#subtitle: "Papers that mention or cite the ALA"
title-block-banner: "#E06E53"
title-block-banner-color: body
toc: false
format: 
  html: 
    include-after-body: _footer.html
    self-contained: true
freeze: true
---

# Modéliser l'effectif et la distribution spatiale des ragondins et les zones d’interaction avec les humains en lien avec des scénarios de changements environnementaux (urbanisation, climat).

Des approches de modélisation statistique sont utilisées pour estimer les effectifs et la distribution spatiale des ragondins et leurs interactions avec les humains, en intégrant des scénarios de changement climatique et d’urbanisation. L’évolution des interactions humain-faune face aux changements environnementaux est simulée à l’aide de modèles mathématiques.

Les travaux sont en cours, notamment dans le cadre de la thèse de Camille Mottier. 

Références : 

- Gimenez, O. (2025) Estimating invasive rodent abundance using removal data and hierarchical models. *NeoBiota* 103: 249-265. <https://doi.org/10.3897/neobiota.103.145876>
