project:
  type: website
  render:
    - "*.qmd"
    - "!archive/"

website:
  title: "LeptoNex"
  description: "Le site web du projet LeptoNex"
  # open-graph:
  #   image: twitter-card-preview_frog-small.png
  #   image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  # twitter-card:
  #   image: twitter-card-preview_frog-small.png
  #   image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  #   card-style: summary_large_image
  site-url: https://leptonex.netlify.app/
  favicon: images/favicon.ico
  navbar:
    background: "#222322"
    foreground: "#FFFFFF"
    title: ""
    # search: false
    # logo: images/logos/ALA_Logo_Inline_REV-RGB.png
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - text: "Projet"
        menu:
        - href: research/shs/index.qmd
          text: "Sciences sociales"
        - href: research/statistique/index.qmd
          text: "Statistique"
        - href: research/sante/index.qmd
          text: "Santé"
      - href: about/index.qmd
        text: "Equipe"
      - href: posts/index.qmd
        text: "Nouvelles"
      # - href: software/index.qmd
      #   text: "Software"
      # - href: books/index.qmd
      #   text: "Books"
      - href: gallery/index.qmd
        text: "Ressources"
      # - href: https://www.ala.org.au
      #   icon: ala
      - href: https://github.com/oliviergimenez/leptonex
        icon: github

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [theme.css, custom_theme.scss]
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
    include-before-body: _fathom.html

execute:
  freeze: auto


