---
title: "L'équipe"
subtitle: Les membres du projet
format: 
  html: 
    include-after-body: _footer.html
title-block-banner: "#E06E53"
title-block-banner-color: body
---

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#| include: false
library(htmltools)
source("../R/functions.R")
```


<!-- # Notre équipe -->

*Cliquez sur les photos pour accéder à plus d'informations sur les personnes*

```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "https://www.fondationbiodiversite.fr/membre/nathalie-charbonnel/",
  img_src = "../images/people/nathalie.jpg",
  name = "Nathalie Charbonnel",
  text = "Porteuse du projet"
),
create_team_card(
  person_page = "https://oliviergimenez.github.io/",
  img_src = "../images/people/olivier.jpg",
  name = "Olivier Gimenez",
  text = "Porteur du projet"
),
create_team_card(
  person_page = "https://www.cefe.cnrs.fr/fr/recherche/ines/ibc/896-c/2818-nicolas-lescureux",
  img_src = "../images/people/nicolas.jpg",
  name = "Nicolas Lescureux",
  text = "Participant"
)
)
tags$div(class = "row", # Create a row for 3 team-member cards
         
create_team_card(
  person_page = "https://www.cefe.cnrs.fr/fr/recherche/ines/ibc/896-c/4287-romain-duda",
  img_src = "../images/people/romain.jpg",
  name = "Romain Duda",
  text = "Participant"
),
create_team_card(
  person_page = "https://pathologie-vegetale.paca.hub.inrae.fr/equipes-de-recherche/virologie/equipe-virologie/berthier-karine",
  img_src = "../images/people/karine.png",
  name = "Karine Berthier",
  text = "Participante"
),
)
```

